name: Update CHANGELOG

on:
  push:
    branches:
      - dev

permissions:
  contents: write  # 允许写入仓库内容

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Generate CHANGELOG
        run: |
          # Initialize CHANGELOG if it doesn't exist
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi

          # Get the last commit timestamp from the CHANGELOG
          last_commit_timestamp=$(git log -1 --pretty=format:"%ct" CHANGELOG.md 2>/dev/null)

          # Determine if we should get all commits or only new ones
          if [ -z "$last_commit_timestamp" ]; then
            # If CHANGELOG.md is new, get all commits
            git log --no-merges --pretty=format:"%ad | %h | %s" --date=format:'%Y-%m-%d %H:%M:%S' > CHANGELOG_TEMP.md
          else
            # Get all commits after the last commit in CHANGELOG
            git log --no-merges --pretty=format:"%ad | %h | %s" --date=format:'%Y-%m-%d %H:%M:%S' --after="$(date -d @$last_commit_timestamp '+%Y-%m-%d %H:%M:%S')" > CHANGELOG_TEMP.md
          fi

          # Format CHANGELOG from temporary file
          if [ -s CHANGELOG_TEMP.md ]; then
            current_date=""
            while IFS=' | ' read -r date hash message; do
              if [[ $current_date != $date ]]; then
                current_date=$date
                echo "## $current_date" >> CHANGELOG.md
              fi
              echo "- $message (commit: $hash)" >> CHANGELOG.md
            done < CHANGELOG_TEMP.md
          fi

          # Clean up temporary file
          rm CHANGELOG_TEMP.md

          # Stage the CHANGELOG.md file
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md" || echo "No changes to commit"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
